### PR TITLE
Feat: allow skipping non-presented items to unblock default values for all remaining items on test timeout

### PR DESCRIPTION
**Pull request by alexeyvy**
Ticket: https://oat-sa.atlassian.net/browse/TR-1432

Allow skipping non-presented items to unblock submitting default responses on test timeout

### CODE REVIEW

**Review by m-lagarde — CHANGES_REQUESTED** [review]
Can we add tests please? :)

**Comment by alexeyvy** [comment]
>Can we add tests please? :)
done @m-lagarde

**Review by julien-sebire — CHANGES_REQUESTED** [review]
This looks good, just two things:
- the name of the feature: We want to submit a default value response for non-presented items, not just to skip them. In CG implementation, skipping actually submits a default response (and consumes an attempt) but it's because our implementation is a little faulty. NG's implementation doesn't submit default value response when skipping so the name of the parameter and title of PR should be changed to reflect the intention.
- please add tests.

**Comment by alexeyvy** [comment]
@julien-sebire 
1) PR renamed
2) test were added already

**Review by julien-sebire — APPROVED** [review]

**Review by emgolubev — APPROVED** [review]
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [x] Documentation is updated according to changes (if applicable)

**Pull request closed without merging**
