### PR TITLE
Fix/tr 1605/preconditions assessmentsection level

### PR DESCRIPTION
**Pull request by bugalot**
### Description

This PR appears in the context of resolving AUT-753, TR-1607, TR-1605 and TR-1606. It seems this bug fix will solve them all in a row :crossed_fingers: !

Long story short, the `preConditions`, to whatever they were bound to (`assessmentSection` or `assessmentItemRef`), were always behaving being bound to an `assessentItemRef`. As a result, a `preCondition` returning true, bound to an `assessmentSection` was leading to always behave as it was bound to the first `assessmentItemRef` of the `assessmentSection`.

This is now solved at the `assessmentTestSession` instantiation level, where the `preConditions` are applied to all `routeItems` that are children to the `sectionPart` (parent class of `assessmentSection` and `assessmentItemRef`) the `preCondition` belong to.

Enjoy :sweat_smile:  !

### Appendix

**General:** 
the existing unit tests were all about `assessmentItemRef` based `preCondition`s. They continue to validate the appropriate behaviour of the routing engine.

**Hints about the changes:**
* `qtism/runtime/tests/AbstractSessionManager.php`: this is where the magic occurs. Basically, the instantiation is all about flattening the Assessment Graph (it's an N-ary tree so, yes, a Graph) while performing a Dept First Search (DFS Left -> Right) traversal. Instead of applying the `preCondition`s on the first item of the sub-routes (flatten `sectionPart`s) while going up in `sectionPart`s, we apply them on all the children. Yes, logic, but still there for 8 years :sweat_smile: !

* `test/qtismtest/runtime/tests/AssessmentTestSessionPreConditionsTest.php`: this is where the testing of the beast occurs. A first section (`S01`) contains a branchRule in order to go in a second (`S02`) OR third (`S03`) section, depending on your response. The two sections are "guarded" by `assessmentSection` level `preCondition`.

* ` test/samples/custom/runtime/preconditions/preconditions_sections_level_linear.xml`: Assessment Material to be executed to simulate the AssessmentTestSession tested in the Test Case mentioned above.

### CODE REVIEW

**Review by uncleempty — APPROVED** [review]
LGTM

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by julien-sebire — APPROVED** [review]
Approved!

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Review by wazelin — APPROVED** [review]
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

**Pull request merged**
