### PR TITLE
Add phing build file and testing setup target

### PR DESCRIPTION
**Pull request by fdewinne**
This phing target ensures to create a phpunit.xml file based on the phpunit.xml.dist just before executing tests.
You can find setup details in https://continuousphp.com/git-hub/fdewinne/qti-sdk#settings

### CODE REVIEW

**Comment by bugalood** [comment]
Thanks Frédéric ! Can you just remove the .idea directory so I can merge? Thanks a lot :)

**Comment by fdewinne** [comment]
It's done. Sorry, I was pretty sure to not have committed them :(

**Comment by bugalood** [comment]
Beautiful, I finish my work on master and merge !

**Comment by fdewinne** [comment]
You're welcome ;)

**Pull request merged**
