### PR TITLE
fix: unify acceptable latency influence on mmove and jump behavior

### PR DESCRIPTION
**Pull request by boajer**
https://oat-sa.atlassian.net/browse/TR-2459

( deployed at http://test-tr-2459-timeouts.playground.kitchen.it.taocloud.org:49181/ )

### CODE REVIEW

**Review by emgolubev — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by poyuki — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by wazelin — CHANGES_REQUESTED** [review]
WDYT of extending `AssessmentTestSessionTimingTest` cases so that they include the case that's being fixed here?

**Comment by wazelin** [comment]
Please add a tech debt ticket to cover the cases with tests.

**Pull request merged**
