### PR TITLE
Updates dependecies to microseconds library, now in oat-sa organization

### PR DESCRIPTION
**Pull request by Alroniks**
Not merge! 

Can be merged after Lionel will add dtms library to packagist.

### CODE REVIEW

**Comment by Alroniks** [comment]
I cannot assign, so just mention for your attention @bugalot

**Comment by bugalot** [comment]
Can you poke me when the package is available on packagist ? Thanks for the contribution !

**Comment by Alroniks** [comment]
@bugalot lib-tao-dtms now on packagist and also I've tested linked libraries and extensions and it works for me (tests related to time passes). So, you can merge it.

**Comment by bugalot** [comment]
Thanks @Alroniks  this is the next on my task list.

**Comment by Alroniks** [comment]
Close, because created new, more related https://github.com/oat-sa/qti-sdk/pull/34

**Pull request closed without merging**
