### PR TITLE
Changed regex for QTI class producing too many steps.

### PR DESCRIPTION
**Pull request by julien-sebire**
QTI class validation is producing thousands of steps due to under-optimized regex, making PHP give up at one moment. Just changed the regex to a simpler one.

### CODE REVIEW

**Review by bartlomiejmarszal — APPROVED** [review]
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Comment by julien-sebire** [comment]
>     * [x]  New code is covered by tests (if applicable)
> 
>     * [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
> 
>     * [x]  New code is respecting code style rules
> 
>     * [x]  New code is respecting best practices
> 
>     * [x]  New code is not subject to concurrency issues (if applicable)
> 
>     * [ ]  Feature is working correctly on my local machine (if applicable)
> 
>     * [x]  Acceptance criteria are respected
> 
>     * [x]  Pull request title and description are meaningful

What is not working on your machine?

**Review by mike-ionut-mihai-sandu-tao — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Comment by julien-sebire** [comment]
Hi @mike-ionut-mihai-sandu-tao 
What is not working in your machine?

**Comment by mike-ionut-mihai-sandu-tao** [comment]
good job @julien-sebire , please assign someone to merge , 
and them please release this fix as it is a blocker issue for authoring squad

**Pull request merged**
