### PR TITLE
Microseconds

### PR DESCRIPTION
**Pull request by Alroniks**
Partially related to this task https://oat-sa.atlassian.net/browse/TAO-1106

Added support of microseconds to durations

### CODE REVIEW

**Comment by Alroniks** [comment]
Ping @bugalot

**Comment by bugalot** [comment]
Currently under review!

**Comment by bugalot** [comment]
Hi @Alroniks !

Thanks for this PR.

It seems that the unit tests fail randomly. I spent an afternoon to understand what is going wrong, but without success. I can make appear errors at the level of Duration comparisons (equals method) when the CPU is under heavy load (I used cpuburn package with ubuntu). Comparison errors are very small, but exists. Usually, it breaks between a "non-microsecond" duration (e.g. PT5S) and another one with a very small difference (e.g. PT5.000001S). I assume that two DateTime objects are compared (diff method) but the second DateTime object has been instantiated some CPU cycles too late. This is why it appears when the CPU is under heavy load. It makes appear some kind of a "crital section" in the code that has to be found.

Thanks to have a look at this.

Jérôme

**Comment by Alroniks** [comment]
Thank you for notice, @bugalot I have some ideas how fix it, so will send updates after.

**Comment by Alroniks** [comment]
@bugalot Could you provide information about tests that failed. I tried run tests under cpuburn on virtualbox (I use homestead box) and all tests was passed.

**Comment by bugalot** [comment]
Basically, common\datatypes\DurationTest.php can make the error happen, let's say 1 time each 10 attempts (it's a mean). 1 cpuburn (burnP5) is not enough, you need a big full charge with multiple cpuburn processes running, to get 100% CPU usage.

**Comment by Alroniks** [comment]
Use 8 burns:
```
vagrant@homestead:~$ burnP5 & burnP5 & burnP5 & burnP5 & burnP5 & burnP5 & burnP5 & burnP5 &
[1] 15763
[2] 15764
[3] 15765
[4] 15766
[5] 15767
[6] 15768
[7] 15769
[8] 15770
```

And I call from 20 till 100 attemts for DurationTest.php and all passes for me. I will try run tests in mac (not in virtualbox), but don't know how catch it.

**Pull request merged**
